ALTER TABLE "Resume" ADD COLUMN "title" TEXT;
ALTER TABLE "Resume" ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Resume" ADD COLUMN "isPrimary" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Resume" ADD COLUMN "summary" TEXT;
ALTER TABLE "Resume" ADD COLUMN "tags" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Resume" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
